name: phglider-tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11.4
  - erddapy==2.0.1
  - jupyter==1.0.0
  - netcdf4==1.6.4
  - numpy==1.24.3
  - pandas==2.0.2
  - xarray==2023.5.0
  - matplotlib==3.7.1
  - cartopy==0.21.1
  - cmocean==3.0.3
  - geographiclib==2.0
  - gsw==3.6.16
